#pragma once

typedef enum CHAT_COMMAND_TYPE
{
	CHAT_CMD_ERROR = -1,
	CHAT_CMD_USERMESSAGE,
	CHAT_CMD_COMMANDLIST,
	CHAT_CMD_BAN,
	CHAT_CMD_BONK,
	CHAT_CMD_GAMEID,
	CHAT_CMD_GIVE,
	CHAT_CMD_GUESTS,
	CHAT_CMD_IP,
	CHAT_CMD_KICK,
	CHAT_CMD_MIC,
	CHAT_CMD_NAME,
	CHAT_CMD_PRIVATE,
	CHAT_CMD_PUBLIC,
	CHAT_CMD_QUIT,
	CHAT_CMD_PADLIMIT,
	CHAT_CMD_SETCONFIG,
	CHAT_CMD_SPEAKERS,
	CHAT_CMD_UNBAN,
	CHAT_CMD_TAKE,
	CHAT_CMD_FF
} CHAT_COMMAND_TYPE;

class ChatCommand
{
public:
	const CHAT_COMMAND_TYPE type = CHAT_CMD_ERROR;
};